export const emojiMapping = {
  SMILE: ["🙂", ":slight_smile:", ":)"],
  SMILE_CLOSED_EYES: ["😊", ":blush:", ":relaxed:", "^_^"],
  SUNGLASSES: ["😎", "😏", ":sunglasses:", ":dark_sunglasses:", "B)"],
  GRIN: [
    "😀",
    "😁",
    ":smiley:",
    ":smile:",
    ":grin:",
    ":grinning:",
    ":joy:",
    ":D",
  ],
  EX_DEE: ["😆", ":laughing:", ":rofl:", "XD"],
  TONGUE: [
    "👅",
    "😛",
    ":tongue:",
    ":stuck_out_tongue:",
    ":stuck_out_tongue_closed_eyes:",
    ":yum:",
    ":P",
  ],
  WINK: ["😉", ":wink:", ";)"],
  SAD: [
    "🙁",
    "😢",
    ":slight_frown:",
    ":frowning:",
    ":frowning2:",
    ":cry:",
    ":sob:",
    ":(",
    ":'(",
  ],
  ANGRY: ["😠", ":angry:", ":anger:", ":rage:", ">:("],
};
